## 用本地配置

##自定义属性
base:
    config:
        swagger:
            enabled: true
            api-base-package: com.teeya.file
            contact:
                name: ZJH
                email: 18826233829@163.com
                url:
            title: 文件服务器管理api
            description: 文件服务器管理接口
            version: 2.0

##非自定义属性
server:
    port: 7900 # 启动端口
spring:
    application:
        name: file-server
    servlet:
        multipart: # 配置MultipartFile
            max-file-size: 10MB # 最大单个文件大小
            max-request-size: 10MB # 最大请求文件大小
    cloud:
        nacos:
            discovery: # nacos注册中心地址配置
                server-addr: localhost:8848
            config: # nacos配置中心地址配置
                server-addr: localhost:8848
        #sentinel配置
        sentinel:
            transport:
                port: 8719 #指定客户端监控 API 的端口  默认，可不设置
                dashboard: localhost:8080 #控制台的地址
    profiles:
        active: dev # 根据不同环境切换配置环境
    # redis配置
    redis:
        host: localhost
        port: 6379
        password:
    # zipkin配置，链路调用可视化面板
    zipkin:
        enabled: true #默认允许开启
        #base-url: http://localhost:9411/ #zipkin服务器地址（只有sender type为web时才需要配置），sleuth会将数据传输到zipkin服务器 需自行到zipkin官网下载jar包安装运行
        sender:
            type: rabbit #发送方式（一共四种，默认web，需要配置base-url参数；设置其他三项则需要配置mq参数（连接成功后默认会生成一个zipkin的队列名称进行链路消息的发送与消费），无需再配置base-url参数，使用mq的好处能达到解耦，不需关心Zipkin服务器的状态）：activemq，rabbit，kafka，web  当配置了base-url，此项可不配置，默认使用http方式收集
    # sleuth链路跟踪配置
    sleuth:
        sampler:
            # 设置采集日志的百分比，数值范围0-1， 1代表100%采集；可依据环境以及实际情况设置
            probability: 1
    #rabbitmq配置
    rabbitmq:
        host: localhost #ip
        port: 5672 #端口
        username: guest #用户名
        password: guest #密码
        virtual-host: / #虚拟主机 每个virtual-host相当于一个相对独立的RabbitMQ服务器，每个virtual-host之间是相互隔离的
        listener:
            simple:
                retry:
                    enabled: false #监听重试是否可用
                    max-attempts: 5 #最大重试次数
                    initial-interval: 3000 #重试间隔次数
    # jackson配置
    jackson:
        # 以下为时间格式转换全局设置，如果只需局部设置则在时间字段上加注解@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        # 属性值为NULL的字段则不参与序列化，即null值不返回给前端
        default-property-inclusion: non_null
name: file-server  # 测试用
##使用sentinel配置
feign:
    sentinel:
        enabled: true
# 七牛云配置参数
qiniu:
    accessKey: iNffcCO5SH8qw-GgV9L_QGbTH2_xLgEVdZIsq6nW
    secretKey: NSNHLflVqXkOM86sEvxbTew3LEX2fCUf-ifQU5TI
    bucket: huijunzeng
    path: www.baidu.com #外链域名
