## 用本地配置
server:
    port: 7900 # 启动端口
spring:
    application:
        name: file-server
    cloud:
        nacos:
            discovery: # nacos注册中心地址配置
                server-addr: localhost:8848
            config: # nacos配置中心地址配置
                server-addr: localhost:8848
        #sentinel配置
        sentinel:
            transport:
                port: 8719 #指定客户端监控 API 的端口  默认，可不设置
                dashboard: localhost:8080 #控制台的地址
    profiles:
        active: dev # 根据不同环境切换配置环境
    # 数据源mysql配置
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/weblog?characterEncoding=UTF-8&useUnicode=true&useSSL=false
        username: root
        password: 123456
        max-idle: 5
        # 数据源hikari连接池配置
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
            minimum-idle: 10 # 池中维护的最小空闲连接数
            idle-timeout: 60000 # 连接允许在池中闲置的最长时间
            maximum-pool-size: 20 # 池中最大连接数，包括闲置和使用中的连接
            auto-commit: true # 自动提交从池中返回的连接
            pool-name: HikariCP # 连接池的用户定义名称
            max-lifetime: 600000 # 池中连接最长生命周期
            connection-timeout: 30000 # 等待来自池的连接的最大毫秒数
            connection-test-query: SELECT 1 # 指定校验连接合法性执行的sql语句
name: file-server  # 测试用
##使用sentinel配置
feign:
    sentinel:
        enabled: true
##logger_name:o.s.c.b.c.PropertySourceBootstrapConfiguration - [TID: N/A] - message:Error opening logging config file classpath:logback-logstash.xml
 #java.lang.IllegalStateException: Logback configuration error detected:
 #ERROR in ch.qos.logback.classic.joran.action.ContextNameAction - Failed to rename context [nacos] as [logback] java.lang.IllegalStateException: Context has been already given a name
logging: #日志配置文件引入 classpath的默认路径为resources目录下，所以需要在resources目录下添加logback-logstash.xml日志配置文件，假如本地不配置这个，会出现上面的报错信息
    config: classpath:logback-logstash.xml
# 七牛云配置参数
qiniu:
    accessKey: iNffcCO5SH8qw-GgV9L_QGbTH2_xLgEVdZIsq6nW
    secretKey: NSNHLflVqXkOM86sEvxbTew3LEX2fCUf-ifQU5TI
    bucket: huijunzeng
    path: www.baidu.com #外链域名
