## 用本地配置
server:
    port: 9778 # 启动端口
spring:
    application:
        name: authentication-server
    cloud:
        nacos:
            discovery: # nacos注册中心地址配置
                server-addr: 129.211.34.120:8848
            config: # nacos配置中心地址配置
                server-addr: 129.211.34.120:8848
    profiles:
        active: dev # 根据不同环境切换配置环境
        # 数据源mysql配置
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://129.211.34.120:3306/oauth2?characterEncoding=UTF-8&useUnicode=true&useSSL=false
        username: root
        password: 123456

        # 数据源hikari连接池配置
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
            read-only: false # 从池中获取的连接是否默认处于只读模式
            minimum-idle: 5 # 池中维护的最小空闲连接数
            idle-timeout: 3000 # 连接允许在池中闲置的最长时间
            maximum-pool-size: 20 # 池中最大连接数，包括闲置和使用中的连接
            auto-commit: true # 自动提交从池中返回的连接
            pool-name: HikariCP # 连接池的用户定义名称
            max-lifetime: 1200000 # 池中连接最长生命周期
            connection-timeout: 3000 # 等待来自池的连接的最大毫秒数
            connection-test-query: SELECT 'x' FROM DUAL # 指定校验连接合法性执行的sql语句
            validation-timeout: 3000 # 连接将被测试活动的最大时间量
    # redis配置
    redis:
        host: 129.211.34.120
        port: 6379
        password:
name: authentication-server  # 测试用
logging:
    config: classpath:logback-logstash.xml

