## 用本地配置
server:
    port: 9777 # 启动端口
spring:
    application:
        name: authorization-server
    cloud:
        nacos:
            discovery: #nacos注册中心地址配置
                server-addr: 129.211.34.120:8848
    #profiles:
    #    active: dev # 根据不同环境切换配置环境
    redis:
        host: 129.211.34.120
        port: 6379
        password:
name: nacosConfig  #测试用
